name: z5-build-env
channels:
  - conda-forge
dependencies:
  - cmake
  - compilers
  - bzip2
  - lz4-c
  - xz
  - zlib
  - nanobind
  - numpy
  - blosc
  - imageio
  - nlohmann_json
  - zarr >=3
  - tensorstore
  - h5py
