package:
  name:
    z5py
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}
  version:
   {{tagged_version}}


source:
  path: ..


build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - python {{PY_VER}}
    - cmake
    - boost-cpp >=1.63
    - xtensor 0.19.3
    - xtensor-python 0.22.1
    - numpy >=1.15
    - nlohmann_json
    - blosc
    - bzip2
    - xz
    - zlib
  run:
    - python {{PY_VER}}
    - numpy >=1.15
    - blosc
    - bzip2
    - xz
    - zlib


test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v
