cmake . -G "NMake Makefiles" -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%" -DWITH_ZLIB=ON -DWITH_BZIP2=ON -DWITH_BLOSC=ON -DWITHIN_TRAVIS=ON -DBUILD_TESTS=OFF -DBUILD_Z5PY=ON -DWITH_LZ4=ON -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"
cmake --build . --target INSTALL --config Release
